Shopify/theme-check

- README.md
Reverts Shopify/theme-check#113
> Revert "Remove direct link to code editor support"

- README.md
It updated the list in the README.
> Update the list of the README

- README.md
> Add custom check to README

- config/default.yml
- lib/theme_check/checks/template_length.rb
- test/checks/template_length_test.rb
> Exclude content of {% schema %} in line count for TemplateLength

- lib/theme_check/cli.rb
> Add -v, --version flag

- config/default.yml
- lib/theme_check/checks/parser_blocking_javascript.rb
- test/checks/parser_blocking_javascript_test.rb
In this PR:
* Turn the rule on by default
* Allow inline script tags
> Enable ParserBlockingJavaScript rule by default and fixup

- lib/theme_check.rb
- lib/theme_check/version.rb
> Fixup version flag

- lib/theme_check/offense.rb
- test/offense_test.rb
> Fix end_column issues

- lib/theme_check/offense.rb
- test/offense_test.rb
> Actually, this is the fix for #164

- lib/theme_check/offense.rb
- test/offense_test.rb
> Refactor start and end Position logic

- README.md
No need for this comment anymore.
> Theme Check is supported 🎉 

- data/shopify_liquid/tags.yml
> Add missing liquid tag completion

- docs/checks/asset_size_javascript.md
- docs/checks/matching_schema_translations.md
- docs/checks/matching_translations.md
- docs/checks/missing_required_template_files.md
- docs/checks/missing_template.md
- docs/checks/nested_snippet.md
- docs/checks/parser_blocking_javascript.md
- docs/checks/required_directories.md
- docs/checks/required_layout_theme_object.md
- docs/checks/space_inside_braces.md
- lib/theme_check/checks/matching_schema_translations.rb
- lib/theme_check/checks/missing_required_template_files.rb
- lib/theme_check/checks/missing_template.rb
- lib/theme_check/checks/nested_snippet.rb
- lib/theme_check/checks/parser_blocking_javascript.rb
- lib/theme_check/checks/required_directories.rb
- lib/theme_check/checks/required_layout_theme_object.rb
- lib/theme_check/checks/space_inside_braces.rb
Add documentation for the following checks:
* SpaceInsideBraces
* RequiredLayoutThemeObject
* RequiredDirectories
* ParserBlockingJavaScript
* NestedSnippet
* MissingTemplate
* MissingRequiredTemplateFiles
> Documentation Spree (Part deux)

- CONTRIBUTING.md
- docs/checks/convert_include_to_render.md
- docs/checks/syntax_error.md
- docs/checks/translation_key_exists.md
- docs/checks/undefined_object.md
- docs/checks/unknown_filter.md
- docs/checks/unused_assign.md
- docs/checks/unused_snippet.md
- docs/checks/valid_html_translation.md
- docs/checks/valid_json.md
- docs/checks/valid_schema.md
- lib/theme_check/checks/asset_size_javascript.rb
- lib/theme_check/checks/convert_include_to_render.rb
- lib/theme_check/checks/syntax_error.rb
- lib/theme_check/checks/translation_key_exists.rb
- lib/theme_check/checks/undefined_object.rb
- lib/theme_check/checks/unknown_filter.rb
- lib/theme_check/checks/unused_assign.rb
- lib/theme_check/checks/unused_snippet.rb
- lib/theme_check/checks/valid_html_translation.rb
- lib/theme_check/checks/valid_json.rb
- lib/theme_check/checks/valid_schema.rb
* Add documentation for the following checks:
* SyntaxError
* TranslationKeyExists
* UndefinedObject
* UnknownFilter
* UnusedAssign
* UnusedSnippet
* ValidHTMLTranslation
* ValidJson
* ValidSchema
* ConvertIncludeToRender
* Update CONTRIBUTING.md to suggest adding documentation files
> Documentation Spree (part III)

- README.md
- lib/theme_check/check.rb
- lib/theme_check/checks/asset_size_javascript.rb
- lib/theme_check/checks/convert_include_to_render.rb
- lib/theme_check/checks/default_locale.rb
- lib/theme_check/checks/deprecated_filter.rb
- lib/theme_check/checks/liquid_tag.rb
- lib/theme_check/checks/matching_schema_translations.rb
- lib/theme_check/checks/matching_translations.rb
- lib/theme_check/checks/missing_enable_comment.rb
- lib/theme_check/checks/missing_required_template_files.rb
- lib/theme_check/checks/missing_template.rb
- lib/theme_check/checks/nested_snippet.rb
- lib/theme_check/checks/parser_blocking_javascript.rb
- lib/theme_check/checks/required_directories.rb
- lib/theme_check/checks/required_layout_theme_object.rb
- lib/theme_check/checks/space_inside_braces.rb
- lib/theme_check/checks/syntax_error.rb
- lib/theme_check/checks/template_length.rb
- lib/theme_check/checks/translation_key_exists.rb
- lib/theme_check/checks/undefined_object.rb
- lib/theme_check/checks/unknown_filter.rb
- lib/theme_check/checks/unused_assign.rb
- lib/theme_check/checks/unused_snippet.rb
- lib/theme_check/checks/valid_html_translation.rb
- lib/theme_check/checks/valid_json.rb
- lib/theme_check/checks/valid_schema.rb
- test/documentation_test.rb
- Add link to documentated checks in README
- Add docs_url magic + unit tests
> Documentation Spree Wrap Up

- lib/theme_check/language_server/completion_providers/filter_completion_provider.rb
- lib/theme_check/shopify_liquid/deprecated_filter.rb
- test/language_server/completion_providers/filter_completion_provider_test.rb
> Do not complete deprecated filters

- config/default.yml
- docs/checks/img_width_and_height.md
- lib/theme_check/checks/asset_size_css.rb
- lib/theme_check/checks/asset_size_javascript.rb
- lib/theme_check/checks/img_width_and_height.rb
- lib/theme_check/checks/parser_blocking_javascript.rb
- lib/theme_check/liquid_check.rb
- test/checks/img_width_and_height_test.rb
> Add ImgWidthAndHeight check

- theme-check.gemspec
To include fix for echo tag
Fixes #218
> Bump min Liquid version to 5.0.1

- lib/theme_check/file_system_storage.rb
- lib/theme_check/in_memory_storage.rb
- lib/theme_check/language_server/document_link_engine.rb
- lib/theme_check/storage.rb
- test/language_server_test.rb
> Storage API Refactor / PR follow up

- README.md
- config/default.yml
- docs/checks/remote_asset.md
- lib/theme_check/checks/remote_asset.rb
- test/checks/remote_asset_test.rb
> Add RemoteAsset check

- lib/theme_check/checks/remote_asset.rb
- test/checks/remote_asset_test.rb
Fixes #147
Same bug as last week... But on the new check. I need something with a timeout or a suite of integration tests.
> Fix slow regex in RemoteAsset check

- packaging/homebrew/theme_check.base.rb
> Fix fetch method in brew recipe

- docs/checks/space_inside_braces.md
It's the only check that has auto-correction for now. This at least shows what auto-correct does.
> Add doc for auto-correction of SpaceInsideBraces

- CHANGELOG.md
- RELEASING.md
- lib/theme_check/version.rb
I realized I forgot to update the changelog in the previous release. And maybe last release should have been a minor bump because of Object completion?
Anyways, updated the change log. Anything else missing?
> Bump version

- README.md
- config/default.yml
- lib/theme_check/check.rb
- lib/theme_check/config.rb
- lib/theme_check/disabled_checks.rb
- test/disabled_checks_test.rb
Eg.: To ignore all UnusedSnippet for icon snippets:
```
UnusedSnippet:
ignore:
- snippets/icon-*
```
> Add ability to ignore individual checks using file patterns

- lib/theme_check/tags.rb
That now supports receiving drops/objects as arg
> Update to support new `{% render %}` syntax

- lib/theme_check/language_server/constants.rb
- lib/theme_check/language_server/document_link_engine.rb
- test/language_server/document_link_engine_test.rb
Not sure how to test the language server updates, but the tests passed.
> Adding asset document links #236

- README.md
- lib/theme_check/bug.rb
- lib/theme_check/check.rb
- lib/theme_check/cli.rb
- lib/theme_check/config.rb
- test/cli_test.rb
Fixes #188
Suitable for running theme check in CI.
> Add `--fail-level` CLI flag

- CHANGELOG.md
- docs/checks/asset_size_app_block_css.md
- docs/checks/asset_size_app_block_javascript.md
- lib/theme_check/version.rb
There are new features in this release
> Actually... Bump to 1.1.0

- config/default.yml
- config/theme_app_extension.yml
- docs/checks/pagination_size.md
- lib/theme_check/checks/pagination_size.rb
- test/checks/pagination_size_test.rb
> Adding pagination size check

- lib/theme_check/language_server/handler.rb
- test/language_server_test.rb
> Handle escaped file URIs in language server

- lib/theme_check/checks/remote_asset.rb
- test/checks/remote_asset_test.rb
> Do not flag link tags that aren't stylesheets

- config/default.yml
- docs/checks/template_length.md
- lib/theme_check/checks/template_length.rb
We would like to bump the the TemplateLength to 600.
> Bump templateLength default

- lib/theme_check/checks/pagination_size.rb
- test/checks/pagination_size_test.rb
> Support pagination size as strings

- lib/theme_check/remote_asset_file.rb
- test/checks/asset_size_javascript_test.rb
- test/remote_asset_file_test.rb
> Handle invalid URIs in RemoteAssetFile

- lib/theme_check/checks/asset_size_css.rb
- lib/theme_check/checks/asset_size_css_stylesheet_tag.rb
- lib/theme_check/regex_helpers.rb
- test/checks/asset_size_css_stylesheet_tag_test.rb
- test/checks/asset_size_css_test.rb
> Fix AssetSizeCSS error when size is nil (and more bugs)

- .github/workflows/theme-check.yml
- lib/theme_check/check.rb
- lib/theme_check/cli.rb
Fail CI if theme-check dawn returns exit code 2.
Closes #336
> Shopify/dawn CI crash test

- lib/theme_check/language_server/io_messenger.rb
Printing was being done by multiple threads at the same time which meant
that _sometimes_, the Content-Length strings were being printed out in
between each other. Which meant that the VS Code extension was freaking
out with no error message.
Had to read code in vscode-languageclient to figure that out.
> Fixup a multithreading problem with our IO Messenger

- lib/theme_check/checks/matching_schema_translations.rb
- lib/theme_check/corrector.rb
- lib/theme_check/liquid_node.rb
- lib/theme_check/locale_diff.rb
- lib/theme_check/position.rb
- lib/theme_check/tags.rb
- lib/theme_check/theme_file_rewriter.rb
- test/checks/matching_schema_translations_test.rb
- test/corrector_test.rb
- test/liquid_node_test.rb
- Corrects translations mistakes in schema tags
- Adds missing translation keys
- Removes extra translation keys
1. Adds/removes missing or extra keys 
2. Updates the schema node to reflect changes made to JSON
> Autocorrection `MatchingSchemaTranslations`

- lib/theme_check/corrector.rb
- test/checks/default_locale_test.rb
Fix for broken default locale autocorrection. File was not being written.
> Fix DefaultLocale Correction

- lib/theme_check/checks/translation_key_exists.rb
- test/checks/translation_key_exists_test.rb
Made the TranslationKeyExists check also look for translation keys in the section schema tag. Resolves #473
> Make TranslationKeyExists also check section translations

- data/shopify_liquid/deprecated_filters.yml
- data/shopify_liquid/filters.yml
- test/cli_test.rb
- test/language_server/completion_providers/filter_completion_provider_test.rb
- test/shopify_liquid_test.rb
- Add support for image_tag filter
- Remove unit test io noise in cli_test.rb
> Add image_tag filter support

- config/default.yml
- docs/checks/schema_json_format.md
- lib/theme_check/checks/asset_size_app_block_css.rb
- lib/theme_check/checks/asset_size_app_block_javascript.rb
- lib/theme_check/checks/deprecated_global_app_block_type.rb
- lib/theme_check/checks/matching_schema_translations.rb
- lib/theme_check/checks/pagination_size.rb
- lib/theme_check/checks/schema_json_format.rb
- lib/theme_check/checks/translation_key_exists.rb
- lib/theme_check/checks/valid_schema.rb
- lib/theme_check/liquid_node.rb
- test/checks/schema_json_format_test.rb
- test/language_server/document_change_corrector_test.rb
https://user-images.githubusercontent.com/4990691/143473949-f66a8c62-b8b0-4fb9-bb56-2543407e7c41.mp4
Fixes #16
> Add SchemaJsonFormat check

- lib/theme_check/checks/valid_html_translation.rb
- test/checks/valid_html_translation_test.rb
> Fix missing null check in ValidHTMLTranslation

- lib/theme_check/disabled_checks.rb
- test/disabled_checks_test.rb
> Disable HTML checks inside Liquid comments

- lib/theme_check/json_printer.rb
- test/cli_test.rb
> Handle nil paths in json_printer's sort_by

- lib/theme_check/checks/deprecated_filter.rb
- test/checks/deprecated_filter_test.rb
- pico -> 16x32
- icon -> 32x32
- grande -> 600x600
- etc.
Fixes #596
> Help migrate named sizes in img_url with DeprecatedFilter corrector

- data/shopify_liquid/filters.yml
> Add missing new filters

- test/checks/unused_assign_test.rb
> Add unit test to make sure we support render for as syntax in UnusedAssign

- CONTRIBUTING.md
- TROUBLESHOOTING.md
Encountered an issue with theme-check locally and updated docs with some hints on how to debug 😄
> Update TROUBLESHOOTING.md to include language server stopping guide

- docs/checks/schema_json_format.md
- Fixes some incorrect examples to improve consistency and clarity
- Fixes https://github.com/Shopify/shopify-dev/issues/29447
- Relates to https://github.com/Shopify/shopify-dev/pull/29649
> [Theme Check]: Fix examples in `SchemaJsonFormat`
