lib/theme_check.rb
lib/theme_check/analyzer.rb
lib/theme_check/cli.rb
lib/theme_check/config.rb
lib/theme_check/corrector.rb
lib/theme_check/liquid_check.rb
lib/theme_check/node.rb
lib/theme_check/offense.rb
lib/theme_check/printer.rb
lib/theme_check/template.rb
test/cli_test.rb
test/corrector_test.rb
test/offence_test.rb

This PR adds a simple auto-correct implementation.
This can be triggered with the new flag `-a`
An example of how a check can add corrections
```ruby
add_offense("Space missing after '{{'", node: node) do |corrector|
corrector.insert_before(node, " ")
end
```
**TODO**
Resolves https://github.com/Shopify/theme-check/issues/57

Add auto-correct support

---

config/default.yml
lib/theme_check/checks/undefined_object.rb
test/checks/undefined_object_test.rb

Report on undefined objects
This started as a check to identify typos in [objects exposed in Shopify
themes](https://shopify.dev/docs/themes/liquid/reference/objects). In
order to accomplish that, I needed to identify all variable definitions
local to the theme and compare the remaining set to the global objects
exposed by Shopify.
Without type checking, theme objects are indiscernible from local variable from the viewpoint
of their lookup. Thus this check reports on all variables, be it locally
defined or exposed by Shopify.
```
snippets/price.liquid:96: error: UndefinedObject: Rendered from snippets/product-card.liquid:87, undefined object `show_badges`.
{%- if show_badges -%}
^^^^^^^^^^^^^^^
snippets/pagination.liquid:19: error: UndefinedObject: Rendered from …
```

Report on undefined objects

---

lib/theme_check/checks/undefined_object.rb
test/checks/undefined_object_test.rb

The render tag supports a syntax using a 'with' parameter as well as a 'for' parameter: https://shopify.dev/docs/themes/liquid/reference/tags/theme-tags\#render. This commit extends the check to understand any alias passed as argument.

Extend UndefinedObject check with alias

---

README.md
config/default.yml
data/shopify_liquid/deprecated_filters.yml
lib/theme_check/checks/deprecated_filter.rb
lib/theme_check/shopify_liquid.rb
lib/theme_check/shopify_liquid/deprecated_filter.rb
test/checks/deprecated_filter_test.rb
test/shopify_liquid_test.rb

Implements https://github.com/Shopify/theme-check/issues/8
I chose to write a new filter, instead of extending the UndefinedFilter, because deprecated filters continue to work to support existing themes. Those filters are no longer supported. Additionally, I wanted to make this check return a severity of type suggestion.

Check for deprecated filters

---

lib/theme_check/offense.rb
test/offence_test.rb

Caused an exception in vscode plugin when encountering markup like:
```
{% render 'product-card',
product_card_product: product,
show_vendor: section.settings.show_vendor,
media_size: section.settings.product_image_ratio,
center_align_text: section.settings.center_align_text,
show_full_details: true
%}
```
Because of the multiline, the markup is not found in the `template.full_line(...)`

Fix error when Offense#end_line is called on multiline markup

---

lib/theme_check/analyzer.rb
lib/theme_check/checks/space_inside_braces.rb
lib/theme_check/cli.rb
lib/theme_check/corrector.rb
lib/theme_check/node.rb
lib/theme_check/template.rb
test/checks/space_inside_braces_test.rb
test/corrector_test.rb
test/test_helper.rb

Adds corrector to the double braces space checks so that they can be auto-corrected. Added also a fix to `corrector.rb` to update a node's markup on replace.
I'm hesitant to add the corrector to space check for liquid tags because we are able to check for missing or extra spaces before the closing brace but not after the opening brace.

Add corrector to double braces space check

---

README.md

We'll put it back when it is available outside.

Remove direct link to code editor support

---

lib/theme_check/language_server/handler.rb
test/language_server_test.rb

Resolves #111 
Error occurs when a template moves from having offences to none. Currently we are not publishing diagnostics if a template contains no offence, however the extension would also not get the updated state.

[Language Server] Send empty diagnostics to flush errors

---

theme-check.gemspec

To avoid confusing errors such as #118

Add Ruby 2.7 as a gem requirement

---

theme-check.gemspec

Reverts Shopify/theme-check#120
Shipit doesn't support Ruby 2.7. Revert this requirement for now as we need to push the fix for vscode.

Revert "Add Ruby 2.7 as a gem requirement"

---

lib/theme_check/checks/space_inside_braces.rb
test/checks/space_inside_braces_test.rb

Came across an issue with Space checking between `,:` characters while adding `|`
On an assign tag the check returns the error twice as seen below
since the assign node markup returns the whole content including the variable
assign node markup : `assign max_width = height | times:  image.aspect_ratio`
variable node markup: `height | times:  image.aspect_ratio`
error thrown
```
+"Too many spaces after ':' at templates/index.liquid:1
+Too many spaces after ':' at templates/index.liquid:1"
```
This pr ignores the check if node type is `assign`;

Ignore node on assign type 

---

config/default.yml
lib/theme_check/cli.rb
lib/theme_check/config.rb
lib/theme_check/language_server/handler.rb
lib/theme_check/theme.rb
test/config_test.rb
test/theme_test.rb

In `.theme-check.yml`
```
ignore:
- node_modules/*
- docs/*.json
```
Will ignore all files matching any of those patterns (matched using [`fnmatch`](https://ruby-doc.org/core-2.5.0/File.html#method-c-fnmatch)).
Defaults to `["node_modules/*"]`.
Fixes #128 
I also added a bit more validation to `Config`:
- Check for type, by comparing to default
- Check for unknown configs, by comparing to default
- Ignore custom checks, but validate its config is a Hash

Add config to ignore files / directories

---

data/shopify_liquid/plus_objects.yml
lib/theme_check/checks/undefined_object.rb
lib/theme_check/shopify_liquid/object.rb
test/checks/undefined_object_test.rb

Making an update to allow for additional, optional objects in the checkout.liquid file.
Based off objects listed in Docs: https://shopify.dev/docs/themes/theme-templates/checkout-liquid#optional-objects

Adding checks for shopify plus objects in checkout

---

lib/theme_check/language_server/handler.rb
lib/theme_check/language_server/server.rb
test/language_server_test.rb

Fixes #136 
Switch approach from reporting diagnostic for every templates currently on disk, to only reporting the ones reported previously.
Should report less diagnostics, and handle file deletion.

Fix VSCode problems not clearing problems when file is deleted

---

.rubocop.yml
config/default.yml
lib/theme_check/checks/undefined_object.rb

See #134 for a previous attempt at a fix. But we ended up recommending to use `default` on all optional parameters. But this is not a good solution.
See context in: https://shopify.slack.com/archives/C01F4ASU4G7/p1613572406096700?thread_ts=1613513255.092400&cid=C01F4ASU4G7
Can be turned back on w/ `ignore_snippets: false`
Fixes #159

Ignore snippets in UndefinedObject

---

lib/theme_check/checks/undefined_object.rb
lib/theme_check/checks/unused_assign.rb
test/checks/undefined_object_test.rb
test/checks/unused_assign_test.rb

Both checks use recursion, and had no stop condition.
Not sure about the one in `UndefinedObject`, but it seems to work 🤞 
Fixes #165

Fix possible stack overflows in UnusedAssign and UndefinedObject

---

lib/theme_check/cli.rb
test/cli_test.rb

Resolves #100
Running theme-check with the `--init` flag will not run the checks, instead it will check if a `.theme-check.yml` config file is present. If it is it will abort and print that the file exists, if not it will create a new file that is cloned from `config/default.yml`.

Add init command to CLI

---

lib/theme_check/checks/undefined_object.rb
test/checks/undefined_object_test.rb

Fixes #186
The issue seemed to be caused by missing line_number for VariableLookup nodes.
Solution: Walk back the parent nodes until we find a line number.

Fix multiple occurrences of UndefinedObject not being reported

---

.rubocop.yml
lib/theme_check/check.rb
lib/theme_check/checks/parser_blocking_javascript.rb
lib/theme_check/config.rb
test/config_test.rb

Add support for multiple check categories
Eg.:
```
categories :liquid, :performance
```
Then, we'll be able to run just the performance checks w/: `theme-check -c performance`

Multiple categories

---

docs/checks/CHECK_DOCS_TEMPLATE.md
docs/checks/template_length.md
lib/theme_check/check.rb
lib/theme_check/checks/template_length.rb
lib/theme_check/language_server/handler.rb
lib/theme_check/language_server/server.rb
test/language_server_test.rb

Add a check documentation template + a way to link to the documentation (from within the repo) in check classes.
This also implements the codeDescription property in diagnostics so that the docs can be accessed from within the editor:
https://screenshot.click/10-29-cjx7r-4asor.mp4
Related #195

Add Documentation Template + TemplateLength Check Documentation

---

config/default.yml
docs/checks/default_locale.md
docs/checks/deprecated_filter.md
docs/checks/liquid_tag.md
docs/checks/matching_schema_translations.md
docs/checks/matching_translations.md
docs/checks/missing_enable_comment.md
lib/theme_check/checks/default_locale.rb
lib/theme_check/checks/deprecated_filter.rb
lib/theme_check/checks/liquid_tag.rb
lib/theme_check/checks/matching_schema_translations.rb
lib/theme_check/checks/matching_translations.rb
lib/theme_check/checks/missing_enable_comment.rb

Add documentation for the following checks:
* MissingEnableComment
* MatchingTranslations
* MatchingSchemaTranslations
* LiquidTag + reduce default to 4 consecutive statements
* DeprecatedFilter
* DefaultLocale

Theme Check Documentation Spree (part 1)

---

config/default.yml
docs/checks/asset_size_css.md
lib/theme_check/checks/asset_size_css.rb
test/checks/asset_size_css_test.rb
test/config_default_test.rb

Fixes #189
This check is a lot like AssetSizeJavaScript but for CSS.
- Disabled by default
- Default value = 100KB
- Link to Alex Russells' Performance Inequality Gap in docs

Add AssetSizeCSS Check

---

lib/theme_check/cli.rb
lib/theme_check/config.rb
test/cli_test.rb

Fixes #211
```
$ head -n 16 /tmp/.theme-check.yml
root: src
require: []
ignore:
- node_modules/*
AssetSizeCSS:
enabled: true
threshold_in_bytes: 1
ConvertIncludeToRender:
enabled: false
LiquidTag:
enabled: false
$ theme-check -C /tmp/.theme-check.yml ../path-to-project
Checking ../path-to-project/src ...
layout/theme.liquid:8: error: AssetSizeCSS: CSS on every page load exceding compressed size threshold (1 Bytes)..
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
581 files inspected, 1 offenses detected, 0 offenses auto-correctable
```

Add `-C, --config path` support

---

.rubocop.yml
Gemfile
lib/theme_check/language_server/server.rb

Use recommended way of installing rubocop-shopify.
Update to latest, w/ support for minitest & rake.

Update & fix Rubocop

---

lib/theme_check/in_memory_storage.rb
lib/theme_check/language_server.rb
lib/theme_check/language_server/completion_engine.rb
lib/theme_check/language_server/completion_provider.rb
lib/theme_check/language_server/completion_providers/render_snippet_completion_provider.rb
lib/theme_check/language_server/constants.rb
lib/theme_check/language_server/document_link_engine.rb
lib/theme_check/language_server/handler.rb
lib/theme_check/language_server/server.rb
test/language_server/document_link_engine_test.rb

Fixes #180 
In this PR:
* Add `{% render '..' %}` completions
* Make snippets in `{% render '..' %}` clickable links
Demo: https://screenshot.click/23-09-71h84-pp23z.mp4
Also: https://screenshot.click/23-22-5tyee-kv5vl.mp4

Add Snippet Completion + Document Links

---

Gemfile
lib/theme_check/checks/translation_key_exists.rb
lib/theme_check/shopify_liquid/deprecated_filter.rb
lib/theme_check/shopify_liquid/filter.rb
lib/theme_check/shopify_liquid/object.rb
lib/theme_check/shopify_liquid/tag.rb

Since we don't commit the Gemfile.lock, CI sometimes use an earlier version of Rubocop and causes unrelated failures.

Pin Rubocop

---

lib/theme_check/file_system_storage.rb
lib/theme_check/in_memory_storage.rb
lib/theme_check/language_server/completion_engine.rb
lib/theme_check/language_server/document_link_engine.rb
lib/theme_check/language_server/handler.rb
test/language_server_test.rb

Fixes #231
Had to refactor a little bit here. Made it clearer that the expected API for read/write on Storage is relative_paths. Also made it so the handler was properly using relative paths when calling the completion and document link engines.
Also:
- Added integration tests for document link (with/without root attribute)
- Refactored all the storage.root.join(...).to_s -> storage.path(...) in tests
- Also made the urls in diagnostics use `file://` instead of `file:`. Since I believe `file://` is the standard. (I'm being redirected in a browser anyway.)

Fix document links from different root

---

.github/workflows/theme-check.yml

Since this is the version used by Homebrew.
Also run those tests on macOS, since this is the most popular setup for running theme check.

Run tests on Ruby 3.0 too

---

lib/theme_check.rb
lib/theme_check/exceptions.rb
lib/theme_check/remote_asset_file.rb

Sometimes the size check doesn't work. It's OK to ignore them.

Rescue errors thrown by remote_asset_file

---

lib/theme_check/language_server/handler.rb
test/language_server_test.rb

Fixes #264
Also, I included a small refactor of send_response to fit the protocol spec. There are  [response messages](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#responseMessage) and there are [notification messages](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#notificationMessage). 
I added helper functions to make the distinction a bit clearer and simplify the calls.

Handle LSP initialize with null rootPath + rootUri

---

lib/theme_check.rb
lib/theme_check/bug.rb
lib/theme_check/checks.rb

Should help with debugging hangs, and other errors.
Exception while running `UnusedAssign#on_assign`:
```
RuntimeError: ouch
/Users/ma/src/github.com/Shopify/theme-check/lib/theme_check/checks/unused_assign.rb:32:in `on_assign'
/Users/ma/src/github.com/Shopify/theme-check/lib/theme_check/checks.rb:25:in `block in call_check_method'
/opt/rubies/2.6.6/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/opt/rubies/2.6.6/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/opt/rubies/2.6.6/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/opt/rubies/2.6.6/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/opt/rubies/2.6.6/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/Users/ma/src/github.com/Shopify/theme-check/lib/theme_check/checks.rb:24:in `call_check_method' …
```

Add a message to help debug errors, timeout after 5 sec of running a check

---

lib/theme_check/bug.rb

Fixes runtime issue when installed via Gem:
```
Traceback (most recent call last):
8: from /Users/taylorsteiger/.rbenv/versions/2.7.2/bin/theme-check:23:in `<main>'
7: from /Users/taylorsteiger/.rbenv/versions/2.7.2/bin/theme-check:23:in `load'
6: from /Users/taylorsteiger/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/theme-check-0.8.2/exe/theme-check:4:in `<top (required)>'
5: from /Users/taylorsteiger/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
4: from /Users/taylorsteiger/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
3: from /Users/taylorsteiger/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/theme-check-0.8.2/lib/theme_check.rb:4:in `<top (required)>'
2: from …
```

Making sure version is set before referencing it

---

lib/theme_check/language_server/completion_providers/filter_completion_provider.rb
test/language_server/completion_providers/filter_completion_provider_test.rb

Asking for a completion right after a filter should trigger a list of
available filters:
`{{ foo | `

Fix completion bug in filter_completion_provider

---

.github/workflows/theme-check.yml
lib/theme_check.rb

Triggers an execution of the new Gem, on an empty theme, to catch basic runtime errors. This helps to enforce the expectations outlined in `CONTRIBUTING.md`, and was from discussed briefly in a previous [PR](https://github.com/Shopify/theme-check/pull/288).

Catch some runtime errors in CI/CD

---

lib/theme_check/language_server/server.rb

`String#size` returns the number of characters, but `Content-Length` must be:
> The length of the content part in bytes.
Fixes #276
Might also explain some other weird bugs in VSCode.

Fix Content-Length in LSP responses to use bytesize

---

lib/theme_check/checks/template_length.rb

Whoops! The check instance is shared across all templates, so the `@excluded_lines` counter just kept increasing all the time.

Fix TemplateLength counter not being reseted on each document

---

lib/theme_check/analyzer.rb
lib/theme_check/check.rb
lib/theme_check/checks.rb
lib/theme_check/checks/missing_template.rb
lib/theme_check/json_file.rb
lib/theme_check/language_server.rb
lib/theme_check/language_server/diagnostics_tracker.rb
lib/theme_check/language_server/handler.rb
lib/theme_check/offense.rb
lib/theme_check/template.rb
lib/theme_check/theme.rb
test/language_server/diagnostics_tracker_test.rb
test/language_server_test.rb
test/offense_test.rb

A check is "single-file" if it only depends on the content of a single file.
A check is "whole-theme" if it depends on the content other files in the theme.
By default, a check will be single-file, unless it defines the `on_end` callback method. Because this implies that it depends on other files in the theme.
A check can be explicitly set as whole-theme with:
```ruby
class MissingTemplate < LiquidCheck
single_file false
end
```
With this new concept introduced, we can optimize theme analysis in LSP.
In the context of LSP, we don't need to re-run single-file checks for files that haven't changed.
When we get a `textDocument/didSave`, the following happens:
- On first run: analyze the full theme like before
- On subsequent runs:
1. Run all whole-theme checks
2. Run all single-theme checks, …

Introduce single-file and whole-theme checks & optimize analysis in LSP

---

CONTRIBUTING.md
config/default.yml
docs/checks/parser_blocking_script_tag.md
lib/theme_check.rb
lib/theme_check/analyzer.rb
lib/theme_check/check.rb
lib/theme_check/checks/img_width_and_height.rb
lib/theme_check/checks/parser_blocking_javascript.rb
lib/theme_check/checks/parser_blocking_script_tag.rb
lib/theme_check/html_check.rb
lib/theme_check/html_node.rb
lib/theme_check/html_visitor.rb
lib/theme_check/liquid_check.rb
test/checks/img_width_and_height_test.rb
test/checks/parser_blocking_javascript_test.rb
test/checks/parser_blocking_script_tag_test.rb
test/html_visitor_test.rb

Ends up we can parse `.liquid` files that contain HTML with Nokogumbo (Ruby wrapper around [Gumbo](https://github.com/google/gumbo-parser), we're already using it for validating translations). It will just threat the Liquid bits as text nodes.
With the resulting AST we get from Gumbo, we can now make HtmlCheck look a lot like the LiquidCheck that use the Liquid AST:
```ruby
class ParserBlockingJavaScript < HtmlCheck
def on_script(node)
return unless node.attributes["src"]
return if node.attributes["defer"] || node.attributes["async"] || node.attributes["type"]&.value == "module"
add_offense("Missing async or defer attribute on script tag", node: node)
end
end
```
This removes the need to rely on regexp to parse the HTML. It makes the checks simpler, and more robust.
Fixes #298 
Still need …

Introduce HTML checks

---

config/default.yml
docs/checks/asset_url_filters.md
lib/theme_check/checks/asset_url_filters.rb
lib/theme_check/checks/remote_asset.rb
lib/theme_check/html_node.rb
lib/theme_check/html_visitor.rb
lib/theme_check/liquid_check.rb
test/checks/asset_url_filters_test.rb
test/checks/remote_asset_test.rb
test/html_visitor_test.rb

And move Liquid specifics to a new `AssetUrlFilters` check.
Fixes #305
I see now that it would be better to combine both type of checks into one, so you could check Liquid & HTML at the same time & get the context from both. But I don't see how we could do this, we'd need to merge both ASTs... I don't see how this could be done.
So we're kind of stuck having to do a bit of Liquid parsing inside `HtmlCheck` sometimes.

Convert `RemoteAsset` into an `HtmlCheck`

---

Rakefile
config/default.yml
docs/checks/html_parsing_error.md
lib/theme_check/checks/html_parsing_error.rb
lib/theme_check/html_visitor.rb
test/checks/html_parsing_error_test.rb

The HTML parser we're using (Gumbo) [limits the number of attributes per element to 400, and the maximum depth of the DOM tree to 400 levels](https://github.com/rubys/nokogumbo#attribute-limit-per-element).
This throws an exception that crashes Theme Check, see #317.
We could bump to limits, or remove the limits, but that seems risky to me to parse without limits. So instead I chose the approach of reporting the errors in a new check, similar to `SyntaxError` for reporting Liquid parsing errors.
If any one of the limit is reached, parsing stops, and all HTML offenses on this file are ignored. This is mentioned in the check doc.
Fixes #317

Add `HtmlParsingError` check for reporting errors during HTML parsing

---

lib/theme_check/checks/asset_size_javascript.rb
lib/theme_check/html_check.rb
test/checks/asset_size_javascript_test.rb

Convert `AssetSizeJavaScript` from `LiquidCheck` to `HtmlCheck`.
Makes the `AssetSizeJavaScript` class a subclass of HtmlCheck. Removes the `scripts()` processing method and any regex constants.
Removes the need to rely on regexp to parse the HTML. It makes the checks simpler, and more robust.

Convert `AssetSizeJavaScript` to `HtmlCheck`

---

config/default.yml
docs/checks/deprecate_bgsizes.md
docs/checks/deprecate_lazysizes.md
lib/theme_check/checks/deprecate_bgsizes.rb
lib/theme_check/checks/deprecate_lazysizes.rb
lib/theme_check/checks/img_lazy_loading.rb
test/checks/deprecate_bgsizes_test.rb
test/checks/deprecate_lazysizes_test.rb
test/checks/img_lazy_loading_test.rb

Discourages the use of the `lazySizes` Javascript library(https://github.com/aFarkas/lazysizes) and the `bgSizes `plugin (https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/bgset).
Adds the checks `DeprecateLazysizes` and `DeprecateBgsizes`.
Extracting the `lazySizes` check outside of the current `ImgLazyLoading` check allows us to deprecate lazySizes without it affecting the JS "loading" attribute

`DeprecateLazysizes` and `DeprecateBgsizes`

---

config/default.yml
docs/checks/asset_size_css_stylesheet_tag.md
lib/theme_check/checks/asset_size_css.rb
lib/theme_check/checks/asset_size_css_stylesheet_tag.rb
lib/theme_check/checks/asset_size_javascript.rb
lib/theme_check/liquid_check.rb
lib/theme_check/regex_helpers.rb
test/checks/asset_size_css_stylesheet_tag_test.rb
test/checks/asset_size_css_test.rb

Convert `AssetSizeCSS` from `LiquidCheck` to `HtmlCheck`. Creates a new `LiquidCheck` for the stylesheet tag  called `AssetSizeCssStylesheetTag`.
Makes the `AssetSizeCSS` class a subclass of HtmlCheck. Removes the  processing method and any regex constants.
Removes the need to rely on regexp to parse the HTML. It makes the checks simpler, and more robust.

Convert `AssetSizeCSS` to `HtmlCheck`

---

lib/theme_check/checks/space_inside_braces.rb
test/checks/space_inside_braces_test.rb

Fixes #348
Also logged a new issue to create a check for this #349. I don't think it's related to `SpacesInsideBraces`, so it should not be in this check.

Ignore empty `{{}}` in `SpaceInsideBraces`

---

lib/theme_check/checks/img_width_and_height.rb
lib/theme_check/checks/remote_asset.rb

Offense strings shouldn't have a trailing period ("."), since this is added by ThemeCheck::Printer#print when outputting the errors.

Offending periods

---

config/theme_app_extension.yml

The JS and CSS asset size limits checks are currently set as `error` severity, with the consequence that they are currently blocking partners from uploading theme app extensions that violate these checks.
The simplest fix for our purposes is to change the severity of the checks to `suggestion`.
Some other possibilities:
* Only change the severity of the app block checks. This would help when a partner is bundling their JS/CSS assets within the extension, but doesn't help when the assets are hosted remotely.
* Only change the severity of these checks when checking theme app extensions.  This would require some code refactoring to allow setting check severity from the configuration file.
Thoughts? (cc @charlespwd, @colinbendell)

Change asset size errors into suggestions for theme app extensions

---

lib/theme_check/checks.rb
lib/theme_check/checks/space_inside_braces.rb
lib/theme_check/parsing_helpers.rb
test/checks/space_inside_braces_test.rb
test/parsing_helpers_test.rb

Fixes #376
Fixes #365
The regex was not multiline, so the scanner wasn't properly splitting the string.

Fix newline in outside_of_strings

---

config/default.yml
config/theme_app_extension.yml
docs/checks/app_block_valid_tags.md
lib/theme_check/checks/app_block_valid_tags.rb
test/checks/app_block_valid_tags_test.rb

Resolves https://github.com/Shopify/theme-check/issues/354
This PR adds a check for the following tags in theme app extension blocks since they will be rejected from the backend:
- `{% javascript %}` 
- `{% stylesheet %}`
- `{% include %}`
- `{% section %}`
- `{% layout %}`

Add check for forbidden tags in theme app extension blocks

---

config/default.yml
config/theme_app_extension.yml
docs/checks/missing_template.md
lib/theme_check/checks/missing_template.rb
test/checks/missing_template_test.rb

Fixes #373
Can be a bit confusing w/ the other `ignore`, so I added an example. Hopefully I made it clear enough in the docs.

Add `MissingTemplate` `ignore_missing` option

---

lib/theme_check/language_server/handler.rb

We still need to write to file on open otherwise the buffer will be empty!
Fixes #395

Fix document links not working on open

---

lib/theme_check/analyzer.rb
lib/theme_check/checks/default_locale.rb
lib/theme_check/corrector.rb
lib/theme_check/json_file.rb
lib/theme_check/theme.rb
test/checks/default_locale_test.rb

Makes sure the theme has a default translation file (for example `locales/en.default.json`).
Automatically creates the default translation file if it doesn't already exist.
I chose to add a `create_default_locale_json` method to the corrector class to allow for the creation of the default translation files in a corrector block

Autocorrection `DefaultLocale`

---

data/shopify_liquid/objects.yml
test/shopify_liquid_test.rb

Add the `predictive_search` drop to theme-check. 
fixes #409 
Last week, the new `predictive_search` drop was released and is documented [here](https://shopify.dev/api/liquid/objects/predictive-search).
I followed [this PR](https://github.com/Shopify/theme-check/pull/330) that added new objects to theme-check.

Add new object drop: predictive_search

---

config/default.yml
docs/checks/deprecated_global_app_block_type.md
lib/theme_check/checks/deprecated_global_app_block_type.rb
test/checks/deprecated_global_app_block_type_test.rb

Part of https://github.com/Shopify/shopify/issues/304710
In order for theme sections to [support app blocks](https://shopify.dev/themes/migration#step-8-add-support-for-app-blocks-to-sections), sections need to define a block of type `@app`. This check makes sure that theme sections are not using the [deprecated](https://shopify.dev/changelog/removing-the-global-block-type-in-favour-of-the-app-block-type-in-theme-sections) `@global` global app block type in theme sections.
:-1: Example of **incorrect** theme for this check:
```
{% for block in section.blocks %}
{% if block.type = "@global" %}
{% render block %}
{% endif %}
{% endfor %}
{% schema %}
{
"name": "Product section",
"blocks": [{"type": "@global"}]
}
{% endschema %}
```
:+1: Examples of **correct** code for this check:
```
{% …
```

Add check for global app block type in theme sections

---

lib/theme_check/checks/pagination_size.rb
test/checks/pagination_size_test.rb

The following would break, due to the check trying to lookup the default section setting for `products_per_page`. The check assumed `products_per_page` must be a section setting if it is a `VariableLookup`.
```liquid
{%- assign products_per_page = section.settings.products_per_page -%}
{%- paginate collection.products by products_per_page -%}
```
This PR only runs the check if it can safely assume that the `VariableLookup` is indeed a section setting.
Fixes #428

Make sure the pagination check allows a variable size

---

lib/theme_check/checks/required_directories.rb
lib/theme_check/corrector.rb
lib/theme_check/file_system_storage.rb
lib/theme_check/in_memory_storage.rb
test/checks/required_directories_test.rb

**What does this do?**
Ensures that required directories exist
**How does it do it?**
Automatically creates missing required directories if they don't already exist.
**Why did you pick this approach over other options?**
This approach uses methods on the corrector class to create the directories that are missing

Autocorrection `RequiredDirectories`

---

lib/theme_check/checks/liquid_tag.rb
lib/theme_check/checks/space_inside_braces.rb
lib/theme_check/node.rb
lib/theme_check/position.rb
lib/theme_check/position_helper.rb
test/checks/space_inside_braces_test.rb
test/node_test.rb
test/position_helper_test.rb
test/test_helper.rb

Fixes #420
This fixes a LOT of bugs actually! This bug was like finding a little crack in a wall and then finding you have termites.
1. This is Liquid's `raw` output for the following tag:
```
{%
render
'file'
%}
=> "render\n  'file'\n"
=> "render 'file'\n"
```
As you can see, not only do we _not_ have the whitespace all the way till "render", we also don't have the whitespace between render and 'file'. This breaks all Position calculations since the needle does not exist in the source.
2.  The implementation of `whitespace_trimmed?` didn't account for tags starting in the middle of a line. Or for tags starting on a different line
```
<ul class="{%- if true -%}oh no{% endif %}">
=> not whitespace trimmed!
{%-
render 'oh no'
-%}
=> not whitespace trimmed!
```
3.  The implementation of …

Fix gnarly bug in Node and SpaceInsideBraces

---

lib/theme_check/checks/convert_include_to_render.rb
test/checks/convert_include_to_render_test.rb

See #445 for details. The corrector shouldn't break your site.

Disable ConvertIncludeToRender corrector

---

lib/theme_check/html_node.rb
lib/theme_check/html_visitor.rb
lib/theme_check/regex_helpers.rb
test/html_visitor_test.rb

Fixes #441
<s>
Couldn't figure out why replace_placeholder was finding liquid tags that
didn't contain an index but this way I'm sure that both of the following
will be true:
1. There definitely _is_ an index. (because the regex guarantees it)
2. It would take 1296 liquid tags/variables for an overflow to be
possible on an empty tag.
</s>
See comments below. Figured it out.

Fix undefined method [] of nil in replace_placeholders

---

lib/theme_check/checks.rb
lib/theme_check/node.rb
test/node_test.rb

Turns out that `{%comment%}`.raw is `"comment "`. This led the Position
class to be unable to find `"comment "` in the source which led to
start_index being undefined and causing this nil error.
You're guaranteed to find `{%comment%}`.tag_name so we should be good to go.
Fixes #452

Fix `Undefined method `-' for nil:NilClass` in Node

---

lib/theme_check/liquid_node.rb
lib/theme_check/position.rb
test/checks/space_inside_braces_test.rb
test/liquid_node_test.rb

Opened dawn with 1.6.1 and saw a bunch of false positives caused by https://github.com/Shopify/theme-check/pull/454.
At some point, I'll have enough unit tests. Really wish we had actual line/col or start_index/end_index in liquid instead. This hack seems really brittle :(.

SpaceInsideBraces fixup for tags without arguments

---

lib/theme_check/exceptions.rb
test/remote_asset_file_test.rb

Handle Errno::EADDRNOTAVAIL in RemoteAsset

---

lib/theme_check/html_node.rb
lib/theme_check/html_visitor.rb
lib/theme_check/regex_helpers.rb
test/checks/remote_asset_test.rb
test/html_node_test.rb

We had issues with our parsing hack. When the liquid had new lines in
it, the #{id}######## hack messed with the line numbers.
Also learned today that the HTML parser doesn't provide an accurate
.to_html value. It is _built_ and not what we provided in the source.
Therefore the two are not equal. The only way to find the source markup
is to look for the tag starting at that line in the source itself. Which
we do in this PR.
Also implemented start/end position methods for the HtmlNode while we're
at it.
Also added tests for HtmlNode#markup,#line_number and position methods.
Fixes #502

Fix Liquid in HTML parsing

---

README.md
lib/theme_check.rb
lib/theme_check/language_server.rb
lib/theme_check/language_server/client_capabilities.rb
lib/theme_check/language_server/configuration.rb
lib/theme_check/language_server/diagnostics_engine.rb
lib/theme_check/language_server/execute_command_engine.rb
lib/theme_check/language_server/execute_command_provider.rb
lib/theme_check/language_server/execute_command_providers/correction_execute_command_provider.rb
lib/theme_check/language_server/execute_command_providers/run_checks_execute_command_provider.rb
lib/theme_check/language_server/handler.rb
lib/theme_check/language_server/io_messenger.rb

Fixes #510
- Add Configuration support
- `themeCheck.checkOnOpen` (default: `true`) makes it so theme check runs on file open.
- `themeCheck.checkOnChange` (default: `true`) makes it so theme check runs on file change.
- `themeCheck.checkOnSave` (default: `true`) makes it so theme check runs on file save.
- Add a `RunChecksExecuteCommandProvider`
- So that a user would be able to run a full theme check manually from a command prompt (e.g. cmd+p in VS Code).
Bonus:
- Add THEME_CHECK_DEBUG_LOG_FILE env var for nvim LSP debugging

Add checkOn{Open,Change,Save} Language Server Configurations

---

lib/theme_check/checks/matching_translations.rb
lib/theme_check/corrector.rb
lib/theme_check/language_server/document_change_corrector.rb
lib/theme_check/locale_diff.rb
lib/theme_check/offense.rb
lib/theme_check/theme.rb
test/checks/matching_translations_test.rb
test/language_server/document_change_corrector_test.rb
test/offense_test.rb
test/theme_test.rb

- Fixup the add_translation correction
- Add the remove_translation correction
- Add the LocaleDiff correction for json files
- Ignore locales/*.schema.json files in MatchingTranslations
Fixes #503

Fix MatchingTranslations check + corrections

---

lib/theme_check/checks.rb
lib/theme_check/html_node.rb
lib/theme_check/theme_file.rb
test/html_node_test.rb

Turns out that everything blows up when we have \r without a followup \n in a file. Nokogiri will handle it and give you a new line, but we didn't and so we ended up with nokogiri telling you something was on line 61 and us not having the newline character and the thing being on line 60.
Fixes #528
Fixes #545

Handle rogue carriage returns

---

lib/theme_check/checks/remote_asset.rb
test/checks/remote_asset_test.rb

Handle media.sources edge case in RemoteAsset

---

README.md
lib/theme_check/analyzer.rb
lib/theme_check/language_server/configuration.rb
lib/theme_check/language_server/diagnostic.rb
lib/theme_check/language_server/diagnostics_engine.rb
lib/theme_check/language_server/diagnostics_manager.rb
lib/theme_check/language_server/execute_command_providers/run_checks_execute_command_provider.rb
lib/theme_check/language_server/handler.rb
lib/theme_check/position.rb
lib/theme_check/position_helper.rb
test/language_server/diagnostics_engine_test.rb

- Speed up partial theme checks & add `"themeCheck.onlySingleFileChecks"`
The difference here is that instead of rerunning all the whole theme checks on change, as we previously did, we only do that on save and open when `"themeCheck.onlySingleFileChecks"` is true. What this means is that whenever you are typing, only the single file checks will run.
This takes ~10ms on my M1 MBP. Not the best machine to do benchmarks on but it's 125x faster than what we had before. So I'm assuming that this 100x+ improvement will transfer to slower machines as well :D
When `"themeCheck.onlySingleFileChecks"` is true, then we disable all whole theme checks entirely and only report failures for the open files. This means that it will always be fast, but it comes at the cost of not having …

Performance Improvements and "themeCheck.onlySingleFileChecks"

---

lib/theme_check/config.rb
test/config_test.rb

Potential fix for #564 
I'm running `theme check` for a root `dist` and trying to require a custom check that lives outside the `dist` folder
- The spec I wrote doesn't break either way, I believe because when run from command line like `shopify theme check --config .config/.theme-check.yml` then `ThemeCheck::Config.load_config` gets a relative path passed in and I'm not 100% sure how to simulate that with the spec

Fix requiring custom check when root is specified

---

config/default.yml
config/theme_app_extension.yml

Fix for https://github.com/Shopify/theme-check/pull/566
We introduced a new arg for UndefinedObject checker without providing a default value for this arg/configuration in `default.yml`. This cause theme-check to report warning: `unknown configuration: UndefinedObject.config_type`
We added this configuration in `default.yml` config file and fixed the values of these configs to a proper `symbol` format in the yml file

Fix unknown configuration issue for UndefinedObject checker

---

CHANGELOG.md

v1.10.3 was never deployed, so commits on main were merged after the original changelog was published. This PR adds those commits to the changelog so we can cut a release for v1.10.3

Bump theme-check version to 1.10.3

---

lib/theme_check/check.rb
lib/theme_check/checks/missing_template.rb
lib/theme_check/config.rb
lib/theme_check/disabled_checks.rb
test/checks/missing_template_test.rb
test/config_test.rb

Fixes #589
Fixes #489
Approach used:
If you're ignoring a file, then we shouldn't be able to flag it as missing. Global and check `ignore` configs are merged with the `ignore_missing` config for the check.

Fix MissingTemplate `ignore` config interactions

---

lib/theme_check/checks/unused_snippet.rb
lib/theme_check/liquid_node.rb
test/checks/unused_snippet_test.rb

Fix handling of `{% render block %}` in UnusedSnippet

---

lib/theme_check/language_server/bridge.rb
lib/theme_check/language_server/server.rb

For some reason, sometimes $stderr.puts err.full_message hangs. And I mean the word used, it _hangs_. It doesn't raise an error. This is annoying because you end up with a 100% CPU instead of logging the error you're meaning to handle. 
This PR wraps the error printing into timeouts so that they print and stop hanging.
Super ironic.
Fixes #622

Prevent server from hanging on error

---

lib/theme_check/disabled_checks.rb
test/disabled_checks_test.rb

Kind of weird edge case. If the theme-check-disable (:all) comment was followed
by another comment, then the theme-check-disable (:all) comment was made to only
apply on the range of the followup comment.
The fix is to not do that when theme-check-disable :all is meant to be
applied to the entire document.
Fixes #583

Fixes theme-check-disable when disable comment is followed by another

---

README.md
docs/checks/asset_size_javascript.md
docs/checks/missing_enable_comment.md
docs/checks/nested_snippet.md
docs/checks/translation_key_exists.md
docs/checks/valid_html_translation.md
lib/theme_check/checks/missing_enable_comment.rb
lib/theme_check/disabled_checks.rb
lib/theme_check/liquid_node.rb
lib/theme_check/liquid_visitor.rb
test/checks/missing_enable_comment_test.rb
test/disabled_checks_test.rb
test/liquid_node_test.rb
theme-check.gemspec

The `#` inline comment tag is coming. This PR adds support for it in theme-check.
Looking forward to using this :+1::
```
{% # theme-check-disable ParserBlockingJavaScript %}
```
Instead of this :-1: :
```
{% comment %}theme-check-disable ParserBlockingJavaScript{% endcomment %}
```
Currently blocked until Shopify/liquid#1498 is merged and we have a new Liquid release.

Add support for `#` inline comment tag

---

lib/theme_check/language_server/diagnostics_engine.rb
lib/theme_check/language_server/execute_command_providers/run_checks_execute_command_provider.rb
lib/theme_check/language_server/handler.rb
lib/theme_check/language_server/versioned_in_memory_storage.rb

Logic was wrong.
When onlySingleFileChecks is on and someone executes the `runChecks`
command. We should do the following:
- Run checks for opened files
- Update diagnostics from opened files
- Do not show "whole theme checks"
Fixes #570

Make runChecks command respect onlySingleFileChecks

---

lib/theme_check/checks/undefined_object.rb
test/checks/undefined_object_test.rb

This PR adds the robots object as „global“ object for the UndefinedObject check. It just adds this for the robots.txt and should through an offense in all other templates.

robots Object in robots.txt file

---

Rakefile
lib/theme_check/shopify_liquid/source_index.rb
lib/theme_check/shopify_liquid/source_manager.rb
shipit.rubygems.yml
test/data/shopify_liquid/documentation/filters.json
test/data/shopify_liquid/documentation/objects.json
test/data/shopify_liquid/documentation/tags.json
test/shopify_liquid/source_manager_test.rb
theme-check.gemspec

Closes #650 
- Create a shipit.rubygems.yml to download docs at release phase 
- Update gemspec to include documentation when pushing package to rubygems
- Create rake command to download theme liquid docs 
- Create new module `SourceManager` to handle downloading/refreshing liquid docs
- Use `SourceManager.download_or_refresh_files` in `SourceIndex` when initializing liquid sources
- Create dummy liquid files for `SourceManager` tests 
👋  The number of additions exploded because of new fixtures for liquid objects, to make reviewing easier:
- [This commit](https://github.com/Shopify/theme-check/pull/661/commits/f03601b40b7cbeb353c0a9724eef18116d1a0851) contains the functionality to download theme liquid docs 
- [This commit](https://github.com/Shopify/theme-check/pull/661/commits/31a3f55b8 …

Download theme-liquid-docs on package deploy or while running theme-check

---

lib/theme_check/language_server/variable_lookup_finder/constants.rb
test/language_server/variable_lookup_finder_test.rb

Fixes #683 
Treats `paginate` in a similar way as `echo`, so that suggestions are shown.
Use cases like `{% paginate customer.orders` will be treated in #687.
Verify that at the cursor position of `{% paginate ⬜️`, suggestions are made.

Suggest objects for `paginate`

---

lib/theme_check/language_server/completion_providers/assignments_completion_provider.rb
lib/theme_check/language_server/variable_lookup_finder/assignments_finder/scope.rb
lib/theme_check/language_server/variable_lookup_finder/assignments_finder/scope_visitor.rb
lib/theme_check/language_server/variable_lookup_finder/tolerant_parser.rb
test/language_server/completion_providers/assignments_completion_provider_test.rb
test/language_server/variable_lookup_finder/assignments_finder_test.rb

Fixes https://github.com/Shopify/theme-check/issues/681, https://github.com/Shopify/theme-check/issues/682, and https://github.com/Shopify/theme-check/issues/684
(I've opened a single PR because the fixes intersect a bit in the code, and I'd have dependent PRs)
---
- 681 https://github.com/Shopify/theme-check/issues/681
- This PR fixes this issue by introducing support to SFR tags in the `TolerantParser`
- https://github.com/Shopify/theme-check/issues/682
- The `AssignmentsCompletionProvider` no longer crashes when it finds an unexpected lookup
- https://github.com/Shopify/theme-check/issues/684
- The `Scope` class now supports literal ranges

Introduce support to range iterations and SFR tags

---

lib/theme_check/language_server/completion_providers/filter_completion_provider.rb
lib/theme_check/shopify_liquid/filter.rb
test/language_server/completion_providers/filter_completion_provider_test.rb
test/shopify_liquid_test.rb

Relates to #656 and #674, rolls back changes to filters suggestion.
- Filters that were previously in `data/shopify_liquid/filters.yml` will not be suggested.
- Theme Check will accept these filters though.
- Verify that code completion for tags is still working as before,
- and that [the tags mentioned in `LABELS_NOT_IN_SOURCE_INDEX`](https://github.com/Shopify/theme-check/blob/fix-656/lib/theme_check/shopify_liquid/tag.rb#L9) keep being suggested.
- Verify that code completion for objects is still working as before,
- and that `customer_address` and `product_variant` keep being suggested, but offer no further suggestions like attribute suggestions.
- :warning: Verify that [the filters mentioned in `LABELS_NOT_IN_SOURCE_INDEX`](https://github.com/Shopify/theme-check/blob/fix-656/lib/theme …

Only suggest filters available in SourceIndex

---

test/language_server/completion_providers/object_completion_provider_test.rb

The CI was passing on https://github.com/Shopify/theme-check/pull/688, however the branch was missing a rebase with `main`.
This PR fixes the CI issue.

`ObjectCompletionProviderd` should not provide completion items that don't live in the `SourceIndex`

---

lib/theme_check/shopify_liquid/documentation/markdown_template.rb
lib/theme_check/shopify_liquid/source_index/base_entry.rb
lib/theme_check/shopify_liquid/source_index/filter_entry.rb
lib/theme_check/shopify_liquid/source_index/object_entry.rb
lib/theme_check/shopify_liquid/source_index/parameter_entry.rb
lib/theme_check/shopify_liquid/source_index/property_entry.rb
lib/theme_check/shopify_liquid/source_index/tag_entry.rb
test/shopify_liquid/documentation/markdown_template_test.rb
test/shopify_liquid/documentation_test.rb
test/shopify_liquid/source_index/property_entry_test.rb

Closes https://github.com/Shopify/theme-check/issues/699
- Update the markdown template to link to shopify-dev in the suggestion title
- Add shopify-dev urls to all entry possibilities for intelligent code completion 
Open a theme and test the following scenarios. Type the following and at the cursor type Ctrl-Space. When a suggestion appears, click the title link. Confirm the link is a sensible suggestion for what you typed. Object properties can be deep linked but tag parameters cannot
`{{ address█ }}`
`{{ address.cit█ }}` 
`{% if█ %}`
`{{ cart | external_video_tag█ }}`
TODO -- I can't seem to find an example for this case where we suggest a filter parameter?

Add shopify-dev link to suggestion title

---

CHANGELOG.md
lib/theme_check/version.rb

v1.14.0 / 2023-01-10
==================
* Add shopify-dev link to code completion suggestion title ([#700](https://github.com/Shopify/theme-check/issues/700))
* Fix examples in `SchemaJsonFormat` ([#698](https://github.com/Shopify/theme-check/issues/698))
* Do not suggest `escape` filter for already escaped strings ([#692](https://github.com/Shopify/theme-check/issues/692))

Bump theme-check version to 1.14.0

---

test/shopify_liquid/source_index_test.rb
test/shopify_liquid_test.rb

This PR removes `assert_equal(exp, act)` in favor of `assert_operator(act, :>=, min_exp)`.
Thus, `Shopify/theme-check` unit tests will no longer break when new types get documented at `Shopify/theme-liquid-docs`.

Avoid strict dependency between `Shopify/theme-check` unit tests and `Shopify/theme-liquid-docs`

---

lib/theme_check/cli.rb
test/cli_test.rb

Fixes part of https://github.com/Shopify/theme-check/issues/706 (a following PR is going to update `Shopify/theme-check-action`)
This PR introduces a flag to synchronously update Theme Check documentation (objects, filters, and tags).
When Theme Check is released, the most updated version of `Shopify/theme-liquid-docs` is embedded. Also, when some new filter is released, local Theme Check instances get auto upgraded asynchronously (so documentation is always updated on developers machines).
However, at CI environments, Theme Check uses the embedded documentation from the latest release, which makes the build of some CI-users fail.
- Download this [filters.json](https://gist.githubusercontent.com/karreiro/2f67793ed1cf15566dfd2833b256e409/raw/1e6adfb67d2b43dfa08ebba219aed8d40dc0a798/filters. …

Introduce `--update-docs` flag to synchronously update Theme Check resources (objects, filters, and tags)

---

.github/workflows/add-theme-check-issues-to-theme-developer-tools-project.yml
.github/workflows/add_theme_check_issues_to_theme_developer_tools_project.yml

Introduce GitHub action to auto add issues to the Theme Developer Tools project.
Requires https://github.com/Shopify/github-actions-access-provider/pull/607

Introduce action to auto add issues to the Theme Developer Tools project

---

CHANGELOG.md
lib/theme_check/version.rb

v1.15.0 / 2023-04-14
==================
* Improve rule for lazy loading to prevent developers from overusing it ([#723](https://github.com/Shopify/theme-check/issues/723))
* Introduce `--update-docs` flag to synchronously update Theme Check resources (objects, filters, and tags) ([#707](https://github.com/Shopify/theme-check/issues/707))

Bump theme-check version to 1.15.0

---

data/shopify_liquid/theme_app_extension_labels.json

Although initially the `section` object was not a valid local-global variable inside app-block context, we are re-introducing it which will allow app-block developers to leverage it to consume section rendering APIs.
Important to note that only the ID property will be exposed.

[TAE] add section context to app blocks

---

config/default.yml
docs/checks/cdn_preconnect.md
lib/theme_check/checks/cdn_preconnect.rb
test/checks/cdn_preconnect_test.rb

The goal of this change is to add a rule that detects and discourages occurrences of:
```html
<link rel="preconnect" href="https://cdn.shopify.com">
```
I described why this kind of preconnect is redundant in the [PR to Dawn](https://github.com/Shopify/dawn/pull/2621).

Add rule to detect redundant preconnect to Shopify CDN
